const products = [
  {id:1,name:'Camiseta Oficial Insanos',category:'Camisetas',price:89.9,image:'img/logo_todos_serao.jpeg',tag:'Mais vendido',stock:{P:5,M:9,G:12,GG:6,XG:3},description:'Camiseta oficial em algodão premium, feita para acompanhar cada quilômetro da sua jornada.'},
  {id:2,name:'Boné Insanos Preto',category:'Bonés',price:79.9,image:'img/logo_operacional.jpeg',tag:'Novo',stock:14,description:'Boné oficial com bordado de alta definição e ajuste traseiro.'},
  {id:3,name:'Corta-vento Insanos',category:'Vestuário',price:219.9,image:'img/logo_caveiras.jpeg',tag:'Edição limitada',stock:{M:2,G:4,GG:3,XG:1},description:'Proteção e estilo para os dias de estrada. Acabamento exclusivo Insanos MC.'},
  {id:4,name:'Bandana Lokas MC',category:'Acessórios',price:34.9,image:'img/logo_as_caveiras.jpeg',tag:'',stock:22,description:'Bandana leve e versátil com arte oficial Lokas MC.'},
  {id:5,name:'Toca Insanos MC',category:'Acessórios',price:49.9,image:'img/logo_cmd_XLVII.jpeg',tag:'',stock:8,description:'Toca de malha confortável com identificação oficial.'},
  {id:6,name:'Moletom Insanos',category:'Vestuário',price:189.9,image:'img/logo_cmd_XLVII_caveira.jpeg',tag:'Últimas peças',stock:{M:0,G:1,GG:0,XG:0,XXG:0},description:'Moletom encorpado, ideal para noites frias e viagens.'},
  {id:7,name:'Óculos Tático',category:'Acessórios',price:119.9,image:'img/logo_operacional.jpeg',tag:'',stock:6,description:'Óculos com proteção e visual marcante.'},
  {id:8,name:'Faca Tática',category:'Equipamentos',price:149.9,image:'img/logo_caveiras.jpeg',tag:'',stock:0,description:'Equipamento tático com acabamento resistente.'}
];
let selectedCategory='Todos', onlyStock=false, shipping=0;
let cart=JSON.parse(localStorage.getItem('regional-jau-cart')||'[]');
const $=s=>document.querySelector(s), money=v=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const productModal=$('#productModal'), loginModal=$('#loginModal'), adminModal=$('#adminModal'), checkoutModal=$('#checkoutModal'), successModal=$('#successModal'), searchInput=$('#searchInput');
const available=(p,size='')=>typeof p.stock==='number'?p.stock:(p.stock[size]||0);
const totalStock=p=>typeof p.stock==='number'?p.stock:Object.values(p.stock).reduce((sum,v)=>sum+v,0);
function renderProducts(){const query=searchInput.value.toLowerCase();const list=products.filter(p=>(selectedCategory==='Todos'||p.category===selectedCategory)&&p.name.toLowerCase().includes(query)&&(!onlyStock||totalStock(p)>0));$('#productGrid').innerHTML=list.map(p=>`<article class="product-card" data-id="${p.id}"><div class="product-image">${p.tag?`<span class="tag ${!totalStock(p)?'out':''}">${totalStock(p)?p.tag:'Esgotado'}</span>`:''}${!p.tag&&!totalStock(p)?'<span class="tag out">Esgotado</span>':''}<img src="${p.image}" alt="${p.name}"></div><div class="product-info"><span class="product-category">${p.category}</span><h3>${p.name}</h3><div class="product-bottom"><span class="price">${money(p.price)} <small>à vista</small></span><button class="add-btn" ${totalStock(p)?'':'disabled'} aria-label="Adicionar ${p.name}">+</button></div></div></article>`).join('')||'<p>Nenhum produto encontrado.</p>';
  document.querySelectorAll('.product-card').forEach(card=>card.onclick=e=>{const product=products.find(p=>p.id==card.dataset.id);if(e.target.closest('.add-btn')) openProduct(product);else openProduct(product);});}
function addToCart(p,size=''){const key=`${p.id}-${size}`, current=cart.find(x=>x.key===key), currentQty=current?.qty||0;if(currentQty>=available(p,size)){alert('Não há mais unidades disponíveis desse produto/tamanho.');return}if(current)current.qty++;else cart.push({id:p.id,key,size,qty:1});saveCart();}
function cartDetails(item){return products.find(p=>p.id===item.id)}
function saveCart(){localStorage.setItem('regional-jau-cart',JSON.stringify(cart));$('#cartCount').textContent=cart.reduce((n,x)=>n+x.qty,0);renderCart();}
function renderCart(){const holder=$('#cartItems');holder.innerHTML=cart.length?cart.map(item=>{const p=cartDetails(item);return `<div class="cart-item"><img src="${p.image}" alt=""><div><h4>${p.name}</h4><p>${item.size?`Tamanho ${item.size} · `:''}Qtd. ${item.qty}</p><b>${money(p.price*item.qty)}</b></div><button data-key="${item.key}" aria-label="Remover item">×</button></div>`}).join(''):'<p class="empty">Sua sacola está vazia.<br>Que tal conhecer nossos produtos?</p>';holder.querySelectorAll('button').forEach(b=>b.onclick=()=>{cart=cart.filter(x=>x.key!==b.dataset.key);saveCart();});$('#cartTotal').textContent=money(subtotal());}
function subtotal(){return cart.reduce((sum,item)=>sum+cartDetails(item).price*item.qty,0)}
function openProduct(p){const sizes=typeof p.stock==='object'?Object.keys(p.stock):[];let size=sizes.find(s=>available(p,s)>0)||'';const soldOut=totalStock(p)===0;$('#modalContent').innerHTML=`<div class="modal-product"><figure><img src="${p.image}" alt="${p.name}"></figure><article><p class="eyebrow">${p.category}</p><h2>${p.name}</h2><p>${p.description}</p><p class="modal-price">${money(p.price)}</p>${sizes.length?`<b>Selecione o tamanho</b><div class="sizes">${sizes.map(s=>`<button class="${s===size?'selected':''}" ${available(p,s)?'':'disabled'} data-size="${s}">${s}</button>`).join('')}</div>`:`<p>${totalStock(p)} unidade${totalStock(p)!==1?'s':''} disponível${totalStock(p)!==1?'is':''}</p>`}<button class="primary-button" id="modalAdd" ${soldOut?'disabled':''}>${soldOut?'Produto esgotado':'Adicionar à sacola'} <span>→</span></button></article></div>`;document.querySelectorAll('.sizes button').forEach(b=>b.onclick=()=>{size=b.dataset.size;document.querySelectorAll('.sizes button').forEach(x=>x.classList.toggle('selected',x===b));});$('#modalAdd').onclick=()=>{addToCart(p,size);productModal.close();openCart();};productModal.showModal();}
const overlay=$('#overlay'),cartPanel=$('#cartPanel');function openCart(){cartPanel.classList.add('open');overlay.classList.add('show')}function closePanels(){cartPanel.classList.remove('open');overlay.classList.remove('show')}
function refreshCheckout(){const sub=subtotal(), payment=document.querySelector('input[name="payment"]:checked')?.value;const discount=payment==='PIX'?sub*.05:0;$('#checkoutSubtotal').textContent=money(sub);$('#checkoutFreight').textContent=shipping?money(shipping):'A calcular';$('#checkoutTotal').textContent=money(Math.max(0,sub-discount)+shipping)}
$('#cartOpen').onclick=openCart;overlay.onclick=closePanels;document.querySelectorAll('.panel .close').forEach(x=>x.onclick=closePanels);document.querySelectorAll('dialog .close').forEach(x=>x.onclick=()=>x.closest('dialog').close());document.querySelectorAll('.category-card').forEach(b=>b.onclick=()=>{selectedCategory=b.dataset.category;document.querySelectorAll('.category-card').forEach(x=>x.classList.toggle('active',x===b));renderProducts();$('#produtos').scrollIntoView({behavior:'smooth'});});
$('#searchOpen').onclick=()=>{$('#searchBar').classList.add('open');setTimeout(()=>searchInput.focus(),100)};$('#searchProducts').onclick=()=>{$('#searchBar').classList.add('open');searchInput.focus()};$('#searchBar .close').onclick=()=>$('#searchBar').classList.remove('open');searchInput.oninput=renderProducts;$('#loginOpen').onclick=()=>loginModal.showModal();$('#adminOpen').onclick=()=>adminModal.showModal();$('#filterStock').onclick=e=>{onlyStock=!onlyStock;e.target.textContent=onlyStock?'Todos os produtos':'Disponíveis';renderProducts()};
$('#loginForm').onsubmit=async event=>{event.preventDefault();const form=new FormData(event.currentTarget),error=$('#loginError'),submit=event.currentTarget.querySelector('button');error.textContent='';submit.disabled=true;try{const response=await fetch('api.php?resource=login',{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({login:form.get('login'),password:form.get('password')})});const raw=await response.text(),contentType=response.headers.get('content-type')||'';let data={};if(!contentType.includes('application/json'))throw new Error('O servidor de login não está disponível. Este site precisa ser publicado em uma hospedagem com PHP e MySQL.');try{data=JSON.parse(raw)}catch{throw new Error('A resposta do servidor está inválida. Tente novamente mais tarde.')}if(!response.ok)throw new Error(data.error||'Não foi possível entrar.');if(!data.user)throw new Error('Resposta de login incompleta.');loginModal.close();if(data.user.role==='administrador'||data.user.role==='diretor_regional')adminModal.showModal();else alert(`Olá, ${data.user.name}! Acesso realizado com sucesso.`)}catch(err){error.textContent=err instanceof Error?err.message:'Não foi possível entrar.'}finally{submit.disabled=false}};
$('#checkout').onclick=()=>{if(!cart.length){alert('Adicione produtos à sua sacola primeiro.');return}closePanels();shipping=0;refreshCheckout();checkoutModal.showModal()};$('#calculateFreight').onclick=()=>{const cep=$('[name="cep"]').value.replace(/\D/g,'');if(cep.length!==8){alert('Informe um CEP válido para calcular o frete.');return}shipping=cep.startsWith('17')?12.9:24.9;refreshCheckout()};document.querySelectorAll('input[name="payment"]').forEach(x=>x.onchange=refreshCheckout);
$('#checkoutForm').onsubmit=e=>{e.preventDefault();if(!shipping){alert('Calcule o frete antes de confirmar o pedido.');return}for(const item of cart){const p=cartDetails(item);if(item.qty>available(p,item.size)){alert(`${p.name} não possui mais estoque suficiente.`);return}}const form=new FormData(e.target), order=`RJ-${String(Date.now()).slice(-6)}`;cart.forEach(item=>{const p=cartDetails(item);if(typeof p.stock==='number')p.stock-=item.qty;else p.stock[item.size]-=item.qty});const payment=form.get('payment'), total=$('#checkoutTotal').textContent;localStorage.setItem('regional-jau-last-order',JSON.stringify({order,total,payment,status:'Aguardando pagamento',date:new Date().toISOString()}));cart=[];saveCart();renderProducts();checkoutModal.close();$('#successText').textContent=`Pedido ${order} criado com sucesso. Total de ${total} via ${payment}. Você receberá as próximas atualizações pelo contato informado.`;successModal.showModal()};$('#successClose').onclick=()=>successModal.close();$('.whatsapp').onclick=()=>alert('Em produção: integração direta ao WhatsApp.');renderProducts();saveCart();
